config/routes.rb
Rails.application.routes.draw do
	devise_for :users, controllers: {
	  registrations: 'users/registrations',
	  sessions: 'users/sessions'
	}
  	# For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  	
  	   resources :messages
  	   # root to: 'notifications#index'
	  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
	 
	  # Websockets resemble this URL
	  
	  get "notifications/index", to: "notifications#index"
  	root to: "chat_rooms#index"

	resources :chat_rooms, only: [:new, :create, :show, :index, :destroy]

	mount ActionCable.server => '/cable'

	# get "dashboard", to: "skills#dashboard"
	get "dashboard", to: "skills#dashboard"

	resources :users, only: [] do
		resources :chat_rooms, only: [:new, :create, :destroy]
		resources :profile, only: [:index]
	end

	resource :profile do
		resources :skills, only: [:edit, :update, :destroy]
		# get "dashboard", to: "profile#dashboard"
	end
	resources :skills

	resources :home, only: [:index]

end

app/models/profile.rb
class Profile < ApplicationRecord
	# has_many :chat_rooms
	belongs_to :user

	has_one_attached :image
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
	before_action :authenticate_user!

	def index
		@user = current_user || User.find(session[:last_logged_out_id])
		@profile = current_user.profile
		
	end

	def show
		@user = current_user
		@profile = current_user.profile
		@skills = current_user.skills.order('skills.rating DESC').distinct
		@new_skill = Skill.new
	end

	def new
		@user = current_user
		@profile = current_user.profile
		@profile = Profile.new
	end

	def create
		# current_user.create_profile(profile_params)

		# current_user.skills << Skill.create(skill_params)

		Profile.create(profile_params.merge(user_id: current_user.id))
		redirect_to new_skill_path
	end

	def edit
		@user = current_user
		@profile = current_user.profile
		@skills = current_user.skills
	end

	def update
		@profile = current_user.profile
		@profile.update(profile_params)
		redirect_to profile_path
	end

	def destroy
		@profile = Profile.find(params[:id])
		@profile.destroy
		redirect_to profile_path
	end

	def dashboard
		@user = current_user
		@skills = current_user.skills
		if params[:language]
		    @result_skills = Skill.where("lower(language) LIKE ?", "%#{params[:language].downcase}%") 
		    @result_users = User.joins(:user_skills, :skills).where(user_skills: {skill_id:  @result_skills}).order('skills.rating DESC').uniq
		 else
		    @skills = Skill.all
  		end
	end	

	private
		def profile_params
			params.require(:profile).permit(:fname, :lname, :nycdastudent, :location, :image, :linkdin, :github)
		end
end

app/helpers/profile_helper.rb
module ProfileHelper
end

app/views/profiles/dashboard.html.erb
<div style="margin: 0px;">
<center>
<button class="bg-dark">
	<%= link_to 'Dashboard', new_profile_path, :style=> 'color:yellow', :class => 'navbar-link' %>
</button>
</center>

app/views/profiles/edit.html.erb
    
<div class="row bg-light" style="height: 100vh;">

    <div class="container m-5 text-dark text-uppercase">

            <h2 class="ml-2">Complete your profile here</h2><br>

            <%= form_for @profile, url: profile_path do |f| %>

                <div class="form-group">
                    
                    <lable class = "col-sm-6 control-label" >
                        First Name <span class="text-danger"> * </span>
                    </lable>
                    <div class="col-sm-6">
                        <%= f.text_field :fname, autofocus: true, autocomplete: "email", class: "form-control", required: true %>
                    </div>
                </div>

                <div class="form-group">
                    <lable class = "col-sm-6 control-label" >
                        Last Name <span class="text-danger"> * </span>
                    </lable>
                    <div class="col-sm-6">
                        <%= f.text_field :lname, autocomplete: "off", class: "form-control", required: true %>
                    </div>
                </div>

                <div class="form-group">
                    <label class = "col-sm-4 control-label">
                        NYCDA Student? ( YES | NO ) <span class="text-danger"> * </span>
                    </label>
                     <div class="col-sm-6">
                        <%= f.select :nycdastudent, options_for_select(["YES","NO"]), prompt: 'Select One', required: true%>
                    </div>
                </div>
               
                <div class="form-group">
                    <lable class = "col-sm-6 control-label" >
                        Linkedin 
                    </lable>
                    <div class="col-sm-6">
                        <%= f.text_field :linkdin, autocomplete: "off", class: "form-control" %>
                    </div>
                </div>

                <div class="form-group">
                    <lable class = "col-sm-6 control-label" >
                        Github 
                    </lable>
                    <div class="col-sm-6">
                        <%= f.text_field :github, autocomplete: "off", class: "form-control" %>
                    </div>
                </div>


                <div class="form-group">
                    <label class = "col-sm-4 control-label">
                        Current City <span class="text-danger"> * </span>
                    </label>
                    <div class="col-sm-6">
                        <%= f.text_field :location, autocomplete: "off", class: "form-control", required: true %>
                    </div>
                </div>

                <div class="form-group">
                     <label class = "col-sm-4 control-label">
                        Upload Image <span class="text-danger"> * </span>
                    </label>
                    <div class="col-sm-6">
                        <%= f.file_field :image, class: "form-control" %>
                    </div>
                </div>

                
                <br>
                <div class="form-group">
                    <div class="col-sm-offset-2 col-sm-6">
                        <%= f.submit "UPDATE", class: "btn btn-primary" %>
                    </div>
                </div>
            <% end %>
    </div>
</div>

app/views/profiles/index.html.erb
 <% unless @profile == nil %>
      <p class="m-5">
            <% if @profile.image.attached? %>
              
                <br>
                <%= image_tag @user.profile.image, :style=> 'height: 250px; width: 250px;' %>
              
      </p>      <% end %>


            <h5 class="m-5 text-uppercase">  NAME: <%= @user.profile.fname %> <%= @user.profile.lname %> 
              <hr>
              Curruntly NYCDA student: <strong> <%= @user.profile.nycdastudent %> </strong>
             <hr>
             Curruntly city location: <strong> <%= @user.profile.location %> </strong>
            </h5>
            <a><strong> <%= @user.profile.linkdin %> </strong></a>
            <a><strong> <%= @user.profile.github %> </strong></a>
            <hr>
            <%= link_to 'Edit', edit_profile_path, :style=> 'color:black', :class => 'navbar-link' %>

            <% else %>

            <%= link_to 'Dashboard', new_profile_path, :style=> 'color:yellow', :class => 'navbar-link' %>
<% end %>

app/views/profiles/new.html.erb
<div class="row bg-light" style="height: 100vh; width: 100vw;">

    <div class="container m-5 text-dark text-uppercase">

            <h2 class="ml-2">Complete your profile here</h2><br>

            <%= form_for @profile, url: profile_path do |f| %>

                <div class="form-group">
                    
                    <lable class = "col-sm-6 control-label" >
                        First Name <span class="text-danger"> * </span>
                    </lable>
                    <div class="col-sm-6">
                        <%= f.text_field :fname, autofocus: true, autocomplete: "email", class: "form-control", required: true %>
                    </div>
                </div>

                <div class="form-group">
                    <lable class = "col-sm-6 control-label" >
                        Last Name <span class="text-danger"> * </span>
                    </lable>
                    <div class="col-sm-6">
                        <%= f.text_field :lname, autocomplete: "off", class: "form-control", required: true %>
                    </div>
                </div>

                <div class="form-group">
                    <label class = "col-sm-4 control-label">
                        NYCDA Student? <span class="text-danger"> * </span>
                    </label>
                    <div class="col-sm-6">
                        <%= f.select :nycdastudent, options_for_select(["YES","NO"]), prompt: 'Select One', required: true%>
                    </div>
                </div>
                
                <div class="form-group">
                    <lable class = "col-sm-6 control-label" >
                        Linkedin 
                    </lable>
                    <div class="col-sm-6">
                        <%= f.text_field :linkdin, autocomplete: "off", class: "form-control" %>
                    </div>
                </div>

                <div class="form-group">
                    <lable class = "col-sm-6 control-label" >
                        Github 
                    </lable>
                    <div class="col-sm-6">
                        <%= f.text_field :github, autocomplete: "off", class: "form-control" %>
                    </div>
                </div>


                <div class="form-group">
                    <label class = "col-sm-4 control-label">
                        Current City <span class="text-danger"> * </span>
                    </label>
                    <div class="col-sm-6">
                        <%= f.text_field :location, autocomplete: "off", placeholder: "New York, NY", class: "form-control", required: true %>
                    </div>
                </div>

                <div class="form-group">
                     <label class = "col-sm-4 control-label">
                        Upload Image <span class="text-danger"> * </span>
                    </label>
                    <div class="col-sm-6">
                        <%= f.file_field :image, class: "form-control", required: true %>
                    </div>
                </div>

                
                <br>
                <div class="form-group">
                    <div class="col-sm-offset-2 col-sm-6">
                        <%= f.submit "CREATE", class: "btn btn-primary" %>
                    </div>
                </div>
            <% end %>
    </div>
</div>

app/views/profiles/show.html.erb
<div class="table-responsive-sm">
<table class="table table-striped">
  <thead>
    <tr>
      <th scope="col">LANGUAGE</th>
      <th scope="col" class="d-none d-md-block">DESCRIPTION</th>
      <th scope="col">RATING</th>
    </tr>
  </thead>
  <tbody>
  <% @skills.each do |skill| %>    
    <tr>
      <td><%= skill.language %> </td>
      <td class="d-none d-md-block"><%= skill.disc %></td>
      <td><%= skill.rating %> / 5</td>
      <td>  <%= link_to 'Edit', edit_profile_skill_path(skill), :style=> 'color:black', :class => 'navbar-link' %> |
            <%= link_to 'Remove', skill_path(skill), method: :delete, data: { confirm: "Are you sure?" }, :style=> 'color:black', :class => 'navbar-link' %>
      </td>
    </tr>
  </tbody>
  <% end %>
</table>
</div>

  <center>
      <%= link_to "ADD MORE SKILL", "#my-modal", :class => "btn",:style=> 'color:black', "data-toggle" => "modal" %>
  </center>


        <div class="modal fade" id="my-modal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true" title="My modal">
          <div class="modal-dialog" role="document">
            <div class="modal-content">
              <div class="modal-header" style="background-color: #FFCB04;">
              <!-- <h3 id="myModalLabel">Modal header</h3> -->
              <h5 class="modal-title">ADD YOUR SKILL HERE</h5>
                <button aria-hidden="true" class="close" data-dismiss="modal" type="button">×</button>
              </div>
              <div class="modal-body bg-light">
                <div class=" m-5 text-dark">
                    <!-- <h2 class="ml-2">ADD YOUR SKILL HERE</h2><br> -->
                      <%= form_for @new_skill do |f| %>
                          <table class="table table-striped">
                            <thead>
                              <tbody>
                                <tr>
                                  <th scope="col">LANGUAGE</th>
                                  <td><%= f.text_field :language, autofocus: true, class: "form-control", required: true %> </td>
                                </tr>
                                <tr>
                                  <th scope="col" class="d-none d-md-block">DESCRIPTION</th>
                                  <td><%= f.text_area :disc, autocomplete: "off", class: "form-control", required: true %></td>
                                </tr>
                                <tr>
                                  <th scope="col">RATING</th>
                                  <td><%= f.select :rating, options_for_select([1,2,3,4,5]), prompt: 'Select One', required: true%></td>
                                </tr>
                              </tbody>
                            </thead>
                          </table>
                          <center>
                            <%= f.submit "ADD", class: "btn btn-primary" %></td>
                          </center>
                      <% end %>
                </div>
              </div>
            </div>
          </div>
        </div>
  </center>


<!-- <button type="button" class="btn btn-lg btn-danger" data-toggle="popover" title="Popover title" data-content="And here's some amazing content. It's very engaging. Right?">Click to toggle popover</button>
<script>
$(function () {
  $('[data-toggle="popover"]').popover()
})
</script> -->