config/routes.rb
Rails.application.routes.draw do
	devise_for :users, controllers: {
	  registrations: 'users/registrations',
	  sessions: 'users/sessions'
	}
  	# For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  	
  	   resources :messages
  	   # root to: 'notifications#index'
	  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
	 
	  # Websockets resemble this URL
	  
	  get "notifications/index", to: "notifications#index"
  	root to: "chat_rooms#index"

	resources :chat_rooms, only: [:new, :create, :show, :index, :destroy]

	mount ActionCable.server => '/cable'

	# get "dashboard", to: "skills#dashboard"
	get "dashboard", to: "skills#dashboard"

	resources :users, only: [] do
		resources :chat_rooms, only: [:new, :create, :destroy]
		resources :profile, only: [:index]
	end

	resource :profile do
		resources :skills, only: [:edit, :update, :destroy]
		# get "dashboard", to: "profile#dashboard"
	end
	resources :skills

	resources :home, only: [:index]

end

app/models/chat_room.rb
class ChatRoom < ApplicationRecord
  # belongs_to :user
  # belongs_to :profile
  belongs_to :owner, class_name: 'User', foreign_key: 'user_id'
  has_many :user_chat_rooms, dependent: :destroy
  has_many :users, :through => :user_chat_rooms
  has_many :messages, dependent: :destroy

  #   delegate :profile, to: :owner
  # delegate :fname, to: :profile, prefix: 'owner'


  def owner_fname
  	owner.profile.fname
  end
end

app/controllers/chat_rooms_controller.rb
class ChatRoomsController < ApplicationController

  def index
    @user = current_user
    # @me = User.find(params[:user_id])
    @profile = current_user.profile
    @chat_rooms = @user.owned_chatrooms + @user.chat_rooms
    # @chat_room = @me.user_chat_rooms
    # @user_name = @user.profile.fname 
    
    if params[:language]
        @result_skills = Skill.where("lower(language) LIKE ?", "%#{params[:language].downcase}%") 
        @result_users = User.joins(:user_skills, :skills).where(user_skills: {skill_id:  @result_skills}).order('skills.rating ASC').uniq
     else
        @skills = Skill.all
      end
  end

  def show

    @user = current_user
    @profile = current_user.profile
  	@chat_room = ChatRoom.includes(:messages).find_by(id: params[:id])
    # if user owned_chatrooms then only he/she can check that chat room and write a message 


    # chat_room
    # id.     user_id
    # 12       8


    # user_chat_room
    # chat_room_id      user_id
    #   12                9
    #.  12                27
    #.  12                32

                                          # @chat_room.users.map(&:id)
    if @chat_room.owner.id == @user.id || @chat_room.user_chat_rooms.map(&:user_id).include?(@user.id)
      #                                     # [9, 27, 32]
  	  @message = Message.new
    else
      redirect_to chat_rooms_path
    end
  end

  def new
    @user = User.find(params[:user_id])
            # User.find_by(id: params[:user_id])
    @profile = current_user.profile
    @chat_room = ChatRoom.new
  end

  def create
    # @user = current_user
    @user = User.find(params[:user_id])
    @profile = current_user.profile
    @chat_room = current_user.owned_chatrooms.build(chat_room_params)
    if @chat_room.save
      @user.user_chat_rooms.create(chat_room_id: @chat_room.id)
  
      flash[:success] = 'Chat room added!'
      redirect_to chat_rooms_path
    else
      render 'new'
    end
  end

  def destroy
    @chat_room = ChatRoom.find(params[:id])
    # @chat_room = current_user.owned_chatrooms.find(params[:id])
    @chat_room.destroy
    redirect_to chat_rooms_path
  end

  private

  def chat_room_params
    params.require(:chat_room).permit(:title)
  end

end

app/helpers/chat_rooms_helper.rb
module ChatRoomsHelper
end

app/views/chat_rooms/_chat_room.html.erb
<div class="container mt-4" >
	
	<blockquote class="blockquote  list-group-item list-group-item-action list-group-item-light ">
	  <p class="mb-0">
	  	<%= link_to "#{chat_room.title}", chat_room_path(chat_room), :class => 'navbar-link text-dark' %>
	  	<span class = "float-right" style="font-size: 1rem;">
			<%= link_to 'Delete', chat_room_path(chat_room),:class => 'navbar-link text-danger', method: :delete, data: { confirm: "Are you sure?" }%>
	  	</span>
	  </p>

	  <footer class="blockquote-footer">Created By
	  	<cite title="Source Title"  style="color:#FFCB04">
	  		<%=  chat_room.owner_fname %>
	  	</cite>
	  </footer>
	  
	</blockquote>
</div>

app/views/chat_rooms/index.html.erb
<div class="container mt-4">
	<% if @chat_rooms.length == 0 %>
	<center>
	<div class="container text-uppercase justify-content-center">
		<div class="jumbotron my-auto">
			<h1 class="ml-4 text-dark "> OH SNAP, YOU DON'T HAVE ANY CHATROOM YET
				
			</h1>
			<p class="ml-4 text-dark"> Don't worry I'll walk you through how it works. </p>

			<!-- Button trigger modal -->
			<button type="button" class="btn btn-warning" data-toggle="modal" data-target="#exampleModalLong">
  				CLICK ME!
			</button>
	</center>
	<% else %>
		<h1 class="ml-4">CHAT ROOMS</h1>
	<!-- 
		<p class="lead" style="color: yellow;">< link_to 'New chat room', new_chat_room_path, class: 'btn btn-primary' %></p>
	 -->
		<ul>
			<% @chat_rooms.each do |chat_room| %>
				<%= render chat_room %>
			<% end %> 
		</ul>
	<% end %> 
</div>
</div>





<!-- Modal -->
<div class="modal fade" id="exampleModalLong" tabindex="-1" role="dialog" aria-labelledby="exampleModalLongTitle" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header" style="background-color: #FFCB04;">
        <h5 class="modal-title" id="exampleModalLongTitle">Step to create a Chatroom</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        

      	<div class="row mt-3">
					<div class="col-9">
						<div class="card bg-light border-0">
						  <div class="card-body">
						    <h5 class="card-title">STEP 1</h5>
						    <p class="card-text"> Please select 
						    	<strong class="text-warning ml-2 mr-2">search</strong>
								 bar in nav
						    </p>
						    <%= image_tag "search-bar.png", :style=> 'height: 100%; width: 100%;', :class => 'border border-secondary',:alt=> "Card image cap"%> 
						    <!-- <p class="card-text"><small class="text-muted">Last updated 3 mins ago</small></p> -->
						  </div>
						</div>
					</div>
					<div class="col-3">

					</div>
				</div>
				<div class="row mt-3">
					<div class="col-3">

					</div>
					<div class="col-9">
						<div class="card bg-light border-0 float-right">
						  <div class="card-body">
						    <h5 class="card-title">STEP 2</h5>
						    <p class="card-text "> Now, when you are here please search the   
						    	<strong class="text-warning ml-2 mr-2">language</strong>
								 you want to learn by the name (one at a time)
						    </p>
						    <%= image_tag "search-bar-lang.png", :style=> 'height: 100%; width: 100%;',:class => 'border border-secondary', :alt=> "Card image cap", :class=> "float-right" %> 
						    <!-- <p class="card-text"><small class="text-muted">Last updated 3 mins ago</small></p> -->
						  </div>
						</div>
					</div>
				</div>
				<div class="row mt-3">
					<div class="col-9">
						<div class="card bg-light border-0">
						  <div class="card-body">
						    <h5 class="card-title">STEP 3</h5>
						    <p class="card-text"> It will give you the list of 
						    	<strong class="text-warning ml-2 mr-2">user</strong>
						    	who added your search language
						    	<strong class="text-warning ml-2 mr-2">HTML</strong>
								 as their skill with rating and little description, which means you will get idea how comfortable they are with
								 <strong class="text-warning ml-2 mr-2">HTML</strong>. 
						    </p>
						    <%= image_tag "search-user.png", :style=> 'height: 100%; width: 100%;',:class => 'border border-secondary', :alt=> "Card image cap"%> 
						    <!-- <p class="card-text"><small class="text-muted">Last updated 3 mins ago</small></p> -->
						  </div>
						</div>
					</div>
					<div class="col-3">

					</div>
				</div>
				<div class="row mt-3">
					<div class="col-3">

					</div>
					<div class="col-9">
						<div class="card bg-light border-0 float-right">
						  <div class="card-body">
						    <h5 class="card-title">STEP 4</h5>
						    <p class="card-text "> You can see one button on left    
						    	<strong class="text-warning ml-2 mr-2">Let's Talk</strong>.
								 Please click on that button.
						    </p>
						    <%= image_tag "letstalkbtn.png", :style=> 'height: 100%; width: 100%;', :alt=> "Card image cap", :class=> "float-right border border-secondary" %> 
						    <!-- <p class="card-text"><small class="text-muted">Last updated 3 mins ago</small></p> -->
						  </div>
						</div>
					</div>
				</div>
				<div class="row mt-3">
					<div class="col-9">
						<div class="card bg-light border-0">
						  <div class="card-body">
						    <h5 class="card-title">STEP 5</h5>
						    <p class="card-text"> When you click on 
						    	<strong class="text-warning ml-2 mr-2">Let's Talk</strong>
						    	button you will see selected user profile with
						    	<strong class="text-warning ml-2 mr-2">Linkedin</strong> and
						    	<strong class="text-warning ml-2 mr-2">Github</strong>
						    	accounnt link on left and on right it will ask you to create
						    	<strong class="text-warning ml-2 mr-2">Chatroom</strong>
								between you and selected user.
						    </p>
						    <%= image_tag "userprofile1.png", :style=> 'height: 100%; width: 100%;', :class => 'border border-secondary',:alt=> "Card image cap"%> 
						    <!-- <p class="card-text"><small class="text-muted">Last updated 3 mins ago</small></p> -->
						  </div>
						</div>
					</div>
					<div class="col-3">

					</div>
				</div>
				<div class="row mt-3">
					<div class="col-3">

					</div>
					<div class="col-9">
						<div class="card bg-light border-0">
						  <div class="card-body">
						    <h5 class="card-title">STEP 6</h5>
						    <p class="card-text"> In title you can type a  
						    	<strong class="text-warning ml-2 mr-2">Chatroom Name. </strong>
						    	Just make it relevent to the
						    	<strong class="text-warning ml-2 mr-2">Lannguage</strong> you gonna talk about.
						    	
						    </p>
						    <%= image_tag "chatroomname1.png", :style=> 'height: 100%; width: 100%;', :class => 'border border-secondary', :alt=> "Card image cap"%> 
						    <!-- <p class="card-text"><small class="text-muted">Last updated 3 mins ago</small></p> -->
						  </div>
						</div>
					</div>
				</div>

				<div class="row mt-3">
					<div class="col-9">
						<div class="card bg-light border-0">
						  <div class="card-body">
						    <h5 class="card-title">STEP 7</h5>
						    <p class="card-text"> It will create a  
						    	<strong class="text-warning ml-2 mr-2">Chatroom</strong>
						   		as you can see in a picture.
						    	Now, click on that chatroom and strat chatting about your problem.
						    </p>
						    <%= image_tag "chatroomslist.png", :style=> 'height: 100%; width: 100%;', :class => 'border border-secondary',:alt=> "Card image cap"%> 
						    <!-- <p class="card-text"><small class="text-muted">Last updated 3 mins ago</small></p> -->
						  </div>
						</div>
					</div>
					<div class="col-3">

					</div>
				</div>

				<div class="row mt-3">
					<div class="col-3">

					</div>
					<div class="col-9">
						<div class="card bg-light border-0">
						  <div class="card-body">
						    <h5 class="card-title">STEP 8</h5>
						     
						    	<strong class="text-warning ml-2 mr-2">HAPPY CODING! </strong>
						    	
						    	
						    </p>
						    <%= image_tag "chat.png", :style=> 'height: 100%; width: 100%;', :class => 'border border-secondary', :alt=> "Card image cap"%> 
						    <!-- <p class="card-text"><small class="text-muted">Last updated 3 mins ago</small></p> -->
						  </div>
						</div>
					</div>
				</div>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
      </div>
    </div>
  </div>
</div>






	

app/views/chat_rooms/new.html.erb
<div class="container mt-4">
	<h1 class="text-uppercase">Create chat room</h1>

	<%= form_for [@user, @chat_room] do |f| %>
	  <div class="form-group">
	    <lable class = "col-sm-6 control-label" >
            <h4>Title 
            	<span class="text-danger"> * </span>
            </h4>
        </lable>
	    <%= f.text_field :title, autofocus: true, class: 'form-control', required: true %>
	  </div>

	  <%= f.submit "CREATE", class: 'btn btn-primary' %>
	<% end %>
</div>

app/views/chat_rooms/show.html.erb
<style type="text/css">
  
#messages {
  max-height: 450px;
  overflow-y: auto;
  .avatar {
    margin: 0.5rem;
  }
}
  
</style>
<div class="container">
  <div class="row">
    <div class="col-sm-4 col-lg-8">
        <div class="container mt-4">
          <%= form_for @message, url: '#' do |f| %>
            <div class="form-group">
              <%= f.label :body %>
              <%= f.text_area :body, class: 'form-control' %>
              <small class="text-muted">From 2 to 1000 characters</small>
            </div>

            <%= f.submit "Send", class: 'btn btn-primary btn-lg' %>
          <% end %>
        </div>
    </div>

    <div class="col-sm-8">
      <div class="container mt-4 col-lg-12">
        <h1><%= @chat_room.title %></h1>
        <div id="messages" data-chat-room-id="<%= @chat_room.id %>" data-user-id="<%= @user.id %>">
          <%= render @chat_room.messages %>
        </div>
      </div>
    </div>
  </div>
</div>