config/routes.rb
Rails.application.routes.draw do
	devise_for :users, controllers: {
	  registrations: 'users/registrations',
	  sessions: 'users/sessions'
	}
  	# For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  	
  	   resources :messages
  	   # root to: 'notifications#index'
	  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
	 
	  # Websockets resemble this URL
	  
	  get "notifications/index", to: "notifications#index"
  	root to: "chat_rooms#index"

	resources :chat_rooms, only: [:new, :create, :show, :index, :destroy]

	mount ActionCable.server => '/cable'

	# get "dashboard", to: "skills#dashboard"
	get "dashboard", to: "skills#dashboard"

	resources :users, only: [] do
		resources :chat_rooms, only: [:new, :create, :destroy]
		resources :profile, only: [:index]
	end

	resource :profile do
		resources :skills, only: [:edit, :update, :destroy]
		# get "dashboard", to: "profile#dashboard"
	end
	resources :skills

	resources :home, only: [:index]

end

app/models/skill.rb
class Skill < ApplicationRecord
	has_many :user_skills, dependent: :destroy
	has_many :user, :through => :user_skills
end

app/controllers/skills_controller.rb
class SkillsController < ApplicationController
	before_action :authenticate_user!

	def index
		@user = current_user
		@profile = current_user.profile
		@skills = current_user.skills.order('skills.rating DESC').uniq
		if params[:language]
		    @result_skills = Skill.where("lower(language) LIKE ?", "%#{params[:language].downcase}%") 
		    @result_users = User.joins(:skills).where('lower(skills.language) LIKE ?', "%#{params[:language].downcase}%").order('skills.rating DESC').uniq
		 else
		    @skills = Skill.all
  		end
	end

	def show
		@user = current_user
		@skills = current_user.skills
  	
	end

	def new
		@user = current_user
		@profile = current_user.profile
		@skills = Skill.new
	end

	def create
		# current_user.create_profile(profile_params)
		# Profile.create(profile_params.merge(user_id: current_user.id))
		@skill = Skill.where('language = ?', params[:language]).first
		if @skill.present?
			current_user.skills << @skill
		else
			@user_skill = Skill.create(skills_params)
			current_user.skills << @user_skill	
		end
		redirect_to profile_path
	end

	def edit
		@user = current_user
		@profile = current_user.profile
		@skills = Skill.find(params[:id])
	end

	def update
		@profile = current_user.profile
		@skills = Skill.find(params[:id])
		@skills.update(skills_params)
		redirect_to profile_path
	end

	def destroy
		@user = current_user
		@profile = current_user.profile
		@skills = Skill.find(params[:id])
		@skills.destroy
		redirect_to profile_path
	end

	def dashboard
		@skills = current_user.skills
		@users = UserSkill.find(params[:id])
	end
	
	private
		def skills_params
			params.require(:skill).permit(:language, :disc, :rating)
		end
end

app/helpers/skills_helper.rb
module SkillsHelper

	def skills_for_result(user_skills, result_skills)
		result_skills.map do |result_skill|
			user_skills.detect {|user_skill| result_skill.id == user_skill.id}
		end.compact
	end
end

app/views/skills/dashboard.html.erb
  <% @users.each do |user| %>
     
    
      <td> <%= user.profile.try(:fname) %> <%= user.profile.try(:lname) %></td>
    
        <%= link_to 'Message', new_user_chat_room_path(user), :style=> 'color:black', :class => 'navbar-link' %>
  
     
      <% end %>

app/views/skills/edit.html.erb
    
<div class="row bg-light" style="height: 100vh;">

    <div class="container m-5 text-dark">

            <h2 class="ml-2">EDIT YOUR SKILL HERE</h2><br>

            <%= form_for @skills do |f| %>

                <div class="form-group">
                    <%= f.label :language, class: "col-sm-2 control-label" %>
                    <div class="col-sm-6">
                        <%= f.text_field :language, autofocus: true, autocomplete: "email", class: "form-control", required: true %>
                    </div>
                </div>

                <div class="form-group">
                    <%= f.label :DEscription, class: "col-sm-2 control-label" %>
                    <div class="col-sm-6">
                        <%= f.text_field :disc, autocomplete: "off", class: "form-control", required: true %>
                    </div>
                </div>               

                <div class="form-group">

                    <%= f.label :Rating, class: "col-sm control-label" %>
                    <div class="col-sm-6">
                        <%= f.select :rating, options_for_select([1,2,3,4,5]), prompt: 'Select One', required: true %>
                    </div>
                </div>

                <div class="form-group">
                    <div class="col-sm-offset-2 col-sm-6">
                        <%= f.submit "ADD", class: "btn btn-primary" %>
                    </div>
                </div>
            <% end %>
    </div>
</div>

app/views/skills/index.html.erb
<div class="container">

<div class="table-responsive-sm">
  <table class="table table-striped text-uppercase">
    <thead>
      <tr>
        <th scope="col">NAME</th>
        <th scope="col">LANGUAGE</th>
        <th scope="col" class="d-none d-md-block">DESCRIPTION</th>
        <th scope="col">RATING</th>
        <!-- <th scope="col">DEBUG</th> -->
      </tr>
    </thead>
    <tbody>
    <% @result_users.each do |user| %>
      <% @matching_results = skills_for_result(user.skills, @result_skills) %> 
       
      <tr>
        <td> <%= user.profile.try(:fname) %> <%= user.profile.try(:lname) %> </td>
        <td> 
          <%= @matching_results.first && @matching_results.first.language %>
        </td>
        <td class="d-none d-md-block"> 
          <%= @matching_results.first && @matching_results.first.disc %>
        </td>
        <td> 
          <%= @matching_results.first && @matching_results.first.rating %>
        </td>
        <td>
          <button type="button" class="btn btn-warning">
           <%= link_to "Let's Talk", new_user_chat_room_path(user), :style=> 'color:black', :class => 'navbar-link' %> 
           </button>
        </td>
       <!--  <td>
          < link_to 'profile', user_profile_index_path(user), :style=> 'color:black', :class => 'navbar-link' %>
        </td> -->

        <!-- <td>
          <%= @matching_results %>
        </td> -->
      </tr>


      <!--  <td>
               link_to 'profile', dashboard_path(@), :style=> 'color:black', :class => 'navbar-link' %>
        </td> -->
      <% end %>
    </tbody>
    
  </table>
</div>
</div>

app/views/skills/new.html.erb
    
<div class="row bg-light" style="height: 100vh;">

    <div class="container m-5 text-dark">

            <h2 class="ml-2">Add your skills here</h2><br>

            <%= form_for @skills do |f| %>

                <div class="form-group">
                    <label class="col-sm-6 control-label">Language
                        <span class="text-danger"> * </span>
                        (EX. HTML)
                    </label>
                    <div class="col-sm-6">
                        <%= f.text_field :language, autofocus: true, class: "form-control", required: true %>
                    </div>
                </div>

                <div class="form-group">
                     <label class="col-sm-2 control-label">Description
                        <span class="text-danger"> * </span>
                    </label>
                    <div class="col-sm-6">
                        <%= f.text_field :disc, autocomplete: "off", class: "form-control", required: true %>
                    </div>
                </div>               

                <div class="form-group">
                     <label class="col-sm-2 control-label">Rating
                        <span class="text-danger"> * </span>
                    </label>
                    <div class="col-sm-6">
                        <%= f.select :rating, options_for_select([1,2,3,4,5]), prompt: 'Select One', required: true%>
                    </div>
                </div>

                <div class="form-group">
                    <div class="col-sm-offset-2 col-sm-6">
                        <%= f.submit "ADD", class: "btn btn-primary" %>
                    </div>
                </div>
            <% end %>
    </div>
</div>

app/views/skills/show.html.erb
<table class="table table-striped">
  <thead>
    <tr>
      <th scope="col">LANGUAGE</th>
      <th scope="col">DISCRIPTION</th>
      <th scope="col">RATING</th>
    </tr>
  </thead>
  <tbody>
  <% @skills.each do |skill| %>    
    <tr>
      <td><%= skill.language %> </td>
      <td><%= skill.disc %></td>
      <td><%= skill.rating %> / 5</td>
      <td>  <%= link_to 'Edit', edit_skill_path(skill), :style=> 'color:black', :class => 'navbar-link' %> </td>
    </tr>
  </tbody>
  <% end %>
</table>

<center>
    <%= link_to 'ADD MORE SKILL', new_skill_path, :style=> 'color:black', :class => 'navbar-link' %>
</center>



        <%= form_tag(skills_path,  method: :get) do %>
                <div class="form-group">
                    <lable class = "col-sm-2 control-label" >
                      Skills
                    </lable>
                    <div class="col-sm-6">
                        <%= text_field_tag :language, nil, class: "form-control" %>
                    </div>
                </div>
                 <%= submit_tag 'Search', name: nil %>
        <% end %>


<% @result_users.each do |user| %>

  <%= user.profile.fname %>

<% end %>