config/routes.rb
Rails.application.routes.draw do
	devise_for :users, controllers: {
	  registrations: 'users/registrations',
	  sessions: 'users/sessions'
	}
  	# For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  	
  	   resources :messages
  	   # root to: 'notifications#index'
	  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
	 
	  # Websockets resemble this URL
	  
	  get "notifications/index", to: "notifications#index"
  	root to: "chat_rooms#index"

	resources :chat_rooms, only: [:new, :create, :show, :index, :destroy]

	mount ActionCable.server => '/cable'

	# get "dashboard", to: "skills#dashboard"
	get "dashboard", to: "skills#dashboard"

	resources :users, only: [] do
		resources :chat_rooms, only: [:new, :create, :destroy]
		resources :profile, only: [:index]
	end

	resource :profile do
		resources :skills, only: [:edit, :update, :destroy]
		# get "dashboard", to: "profile#dashboard"
	end
	resources :skills

	resources :home, only: [:index]

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/chat_room.rb
class ChatRoom < ApplicationRecord
  # belongs_to :user
  # belongs_to :profile
  belongs_to :owner, class_name: 'User', foreign_key: 'user_id'
  has_many :user_chat_rooms, dependent: :destroy
  has_many :users, :through => :user_chat_rooms
  has_many :messages, dependent: :destroy

  #   delegate :profile, to: :owner
  # delegate :fname, to: :profile, prefix: 'owner'


  def owner_fname
  	owner.profile.fname
  end
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :user
  belongs_to :chat_room

  def timestamp
  	created_at.strftime('%H:%M:%S %d %B %Y')
  end
  
  validates :body, presence: true, length: {minimum: 2, maximum: 1000}

  after_create_commit { MessageBroadcastJob.perform_later(self) }

end

app/models/notification.rb
class Notification < ApplicationRecord
	after_create_commit { NotificationBroadcastJob.perform_later(Notification.count)}
end

app/models/profile.rb
class Profile < ApplicationRecord
	# has_many :chat_rooms
	belongs_to :user

	has_one_attached :image
end

app/models/skill.rb
class Skill < ApplicationRecord
	has_many :user_skills, dependent: :destroy
	has_many :user, :through => :user_skills
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :owned_chatrooms, class_name: 'ChatRoom', foreign_key: 'user_id'

  has_many :user_chat_rooms
  has_many :chat_rooms, :through => :user_chat_rooms, dependent: :destroy
  has_many :messages, dependent: :destroy
  has_many :user_skills
  has_many :skills, :through => :user_skills, dependent: :destroy
  has_one :profile
  
  def name
  	email.split('@')[0]
  end
  
end

app/models/user_chat_room.rb
class UserChatRoom < ApplicationRecord
	belongs_to :user
	belongs_to :chat_room
end

app/models/user_skill.rb
class UserSkill < ApplicationRecord
	belongs_to :user
	belongs_to :skill
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
	def index
		
	end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
	before_action :authenticate_user!

	def index
		@user = current_user || User.find(session[:last_logged_out_id])
		@profile = current_user.profile
		
	end

	def show
		@user = current_user
		@profile = current_user.profile
		@skills = current_user.skills.order('skills.rating DESC').distinct
		@new_skill = Skill.new
	end

	def new
		@user = current_user
		@profile = current_user.profile
		@profile = Profile.new
	end

	def create
		# current_user.create_profile(profile_params)

		# current_user.skills << Skill.create(skill_params)

		Profile.create(profile_params.merge(user_id: current_user.id))
		redirect_to new_skill_path
	end

	def edit
		@user = current_user
		@profile = current_user.profile
		@skills = current_user.skills
	end

	def update
		@profile = current_user.profile
		@profile.update(profile_params)
		redirect_to profile_path
	end

	def destroy
		@profile = Profile.find(params[:id])
		@profile.destroy
		redirect_to profile_path
	end

	def dashboard
		@user = current_user
		@skills = current_user.skills
		if params[:language]
		    @result_skills = Skill.where("lower(language) LIKE ?", "%#{params[:language].downcase}%") 
		    @result_users = User.joins(:user_skills, :skills).where(user_skills: {skill_id:  @result_skills}).order('skills.rating DESC').uniq
		 else
		    @skills = Skill.all
  		end
	end	

	private
		def profile_params
			params.require(:profile).permit(:fname, :lname, :nycdastudent, :location, :image, :linkdin, :github)
		end
end

app/controllers/skills_controller.rb
class SkillsController < ApplicationController
	before_action :authenticate_user!

	def index
		@user = current_user
		@profile = current_user.profile
		@skills = current_user.skills.order('skills.rating DESC').uniq
		if params[:language]
		    @result_skills = Skill.where("lower(language) LIKE ?", "%#{params[:language].downcase}%") 
		    @result_users = User.joins(:skills).where('lower(skills.language) LIKE ?', "%#{params[:language].downcase}%").order('skills.rating DESC').uniq
		 else
		    @skills = Skill.all
  		end
	end

	def show
		@user = current_user
		@skills = current_user.skills
  	
	end

	def new
		@user = current_user
		@profile = current_user.profile
		@skills = Skill.new
	end

	def create
		# current_user.create_profile(profile_params)
		# Profile.create(profile_params.merge(user_id: current_user.id))
		@skill = Skill.where('language = ?', params[:language]).first
		if @skill.present?
			current_user.skills << @skill
		else
			@user_skill = Skill.create(skills_params)
			current_user.skills << @user_skill	
		end
		redirect_to profile_path
	end

	def edit
		@user = current_user
		@profile = current_user.profile
		@skills = Skill.find(params[:id])
	end

	def update
		@profile = current_user.profile
		@skills = Skill.find(params[:id])
		@skills.update(skills_params)
		redirect_to profile_path
	end

	def destroy
		@user = current_user
		@profile = current_user.profile
		@skills = Skill.find(params[:id])
		@skills.destroy
		redirect_to profile_path
	end

	def dashboard
		@skills = current_user.skills
		@users = UserSkill.find(params[:id])
	end
	
	private
		def skills_params
			params.require(:skill).permit(:language, :disc, :rating)
		end
end

app/helpers/application_helper.rb
module ApplicationHelper

	 def gravatar_for(user, opts = {})
	    text_field_tag user.profile.fname
	    image_tag user.profile.image, style: 'max-width: 65px; max-height: 55px; min-width: 20px; min-height: 20px'
  	end
end

app/helpers/chat_rooms_helper.rb
module ChatRoomsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/notifications_helper.rb
module NotificationsHelper
end

app/helpers/profile_helper.rb
module ProfileHelper
end

app/helpers/skills_helper.rb
module SkillsHelper

	def skills_for_result(user_skills, result_skills)
		result_skills.map do |result_skill|
			user_skills.detect {|user_skill| result_skill.id == user_skill.id}
		end.compact
	end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Let's Codee</title>
    <meta name="viewport" content="width=device-width">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
     <link href='https://fonts.googleapis.com/css?family=Raleway' rel='stylesheet' type='text/css'>
     <link href="https://fonts.googleapis.com/css?family=Righteous" rel="stylesheet">
    
  </head>

  <body>
    
    <% if user_signed_in? %>
      <!-- <nav class="navbar navbar-expand navbar-dark bg-dark"> -->
      <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <!-- <div class="container"> -->
          <a class="text-white navbar-brand m-2"  style="font-family: Trebuchet MS " href="<%= profile_path %>">LET'S CODE(< >)</a>
          <button type="button" class="navbar-toggler" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false">
            <span class="navbar-toggler-icon"></span>
          </button>

          <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav mr-auto">
              <li class="nav-item m-2">
                <%= link_to 'PROFILE', profile_path, :style=> 'color:#FFCB04', :class => 'navbar-link' %>
              </li>
              <li class="nav-item m-2">
                <%= link_to 'CHAT-ROOMS', chat_rooms_path, :style=> 'color:#FFCB04', :class => 'navbar-link' %>
              </li>

               <li class="nav-item m-2">
                 <%= link_to 'EDIT PROFILE', edit_profile_path, :class => 'navbar-link', :style=> 'color:#FFCB04' %>
              </li>


               <li class="nav-item m-2">
               <%= link_to "LOGOUT", destroy_user_session_path,method: :delete, :class => 'navbar-link', :style=> 'color:#FFCB04'  %>
              </li>
             <!--  <li class="nav-item m-2">
                < link_to "LOGOUT", destroy_user_session_path,  :style=> 'color:yellow',method: :delete, :class => 'navbar-link'  %>
        
              </li> -->

              <li class="nav-item dropdown ml-2 ">
                  <!-- <link_to 'PROFILE', profile_path, :style=> 'color:yellow', :class => 'navbar-link dropdown-toggle active' :id => 'navbarDropdown', role: => "button" %> -->
                  <!-- <a href="<%= profile_path%>" class="nav-link dropdown-toggle active  " id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" style ='color:#FFCB04'>MORE-OPTIONS</a> -->
                  <!-- <div class="dropdown-menu bg-dark" aria-labelledby="navbarDropdown"> -->
                    <!-- < link_to 'EDIT PROFILE', edit_profile_path, :class => 'dropdown-item', :style=> 'color:#FFCB04' %> -->
                    <!-- < link_to "LOGOUT", destroy_user_session_path,method: :delete, :class => 'dropdown-item', :style=> 'color:#FFCB04'  %> -->
                    <!-- <a href="#" class="dropdown-item">Aplicações para a área de saúde</a> -->
                 <!--  </div>
               </li> -->
            </ul>

            <span class="navbar-text">
              <ul class="navbar-nav mr-auto">
               <!-- <li class="text-white nav-item m-2">Welcome, 
                  <strong style="color: #1e87f0;">
                    <%= current_user.email %>
                  </strong>
                </li> -->
                <li class="text-white nav-item mt-2">
                    <%= form_tag(skills_path,  method: :get) do %>
                        <div class="form-group">
                            <%= text_field_tag :language, nil, :class => "mr-1"  %>
                            <%= submit_tag 'SEARCH', name: nil, :class => "btn btn-outline-warning", :style=> 'color:#FFf' %>
                        </div>
                    <% end %>
                </li>
                 <li>
                    <!-- < image_tag "notification_bell.png", :style=> 'height: 40px; width:60px;', :class=> "mt-2"%>
                    <span  id="notification-counter"><%= @counter %></span> -->
                </li>
              </ul>
            </span>  
          </div>
        <!-- </div> -->
      </nav>
    <% end %>

    <div class="row">
       <% unless @user.profile == nil %>
      <div class="col-md-5 col-lg-3 d-none d-md-block" style="background-color: #FFCB04; min-height: 90vh; ">
        <h2 style="padding: 50px 0px 0px 50px;"> LET'S CODE(< >) </h2>
          <% unless @user.profile == nil %>
              <p class="mt-2 ml-5">
                <% if @user.profile.image.attached? %>
                    <br>
                    <%= image_tag @user.profile.image, :style=> 'height: 200px; width: 220px; border-radius: 100%;'%>
                    <!--  < image_tag @user.profile.image, :style=> 'height: 200px; max-width: 250px;' %> -->
                <% end %>
              </p> 

              <h5 class="m-5 text-uppercase ">  NAME: <strong><%= @user.profile.fname %> <%= @user.profile.lname %> </strong>
                <hr>
                NYCDA student: <strong> <%= @user.profile.nycdastudent %> </strong>
                <hr>
                location: <strong> <%= @user.profile.location %> </strong>
                <hr>
                <center>
                  <% unless @user.profile.linkdin.blank? %>
                    <a href="<%= @user.profile.linkdin %>" target = "_blank"> 
                        <%# image_tag "/assets/images/LinkedIn_logo_initials.png", :class => "style_image" %>
                        <img src="https://pngimg.com/uploads/linkedIn/linkedIn_PNG32.png" class="style_image">
                    </a>
                  <% end %>
                  <% unless @user.profile.github.blank? %>
                    <a href="<%= @user.profile.github %>" target = "_blank"> 
                        <!-- < image_tag "github-logo-icon", :class => "style_image" > -->
                        <img src="https://cdn.freebiesupply.com/logos/large/2x/github-icon-logo-png-transparent.png" class="style_image">
                        
                    </a>
                    <% end %>
                </center>
                <!-- < link_to 'Edit', edit_profile_path, :style=> 'color:black', :class => 'navbar-link' %> -->
                <% else %>
                <% if user_signed_in? %>
                <h5 class="m-5 text-uppercase text-dark">
                  <%= link_to 'Dashboard', new_profile_path, :style=> 'color:black', :class => 'navbar-link' %>
                <% end %>
              </h5>
          <% end %>
          <% end %>
      </div>
      <div class="col-sm-12 col-md-7 col-lg-9 bg-light " style="float: left;
        width: 100%">
          <!-- <div class="container"> -->
        <%= yield %>
          <!-- </div> -->
      </div>
    </div>
      
<script src="//netdna.bootstrapcdn.com/bootstrap/3.1.0/js/bootstrap.min.js", data-turbolinks-eval=false ></script>
<script src="//code.jquery.com/jquery-1.11.1.min.js"></script>
  
</body>
</html>